# Ams data merge

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pvlib

## Load data

In [2]:
fname_ams_weather = '../data/nl/ams_data_weather_processed.csv'
fname_ams_energy = '../data/nl/ams_data_energy.csv'
df_ams_weather, df_ams_energy = [pd.read_csv(fname) for fname in [
    fname_ams_weather, fname_ams_energy]]

In [3]:
fname_ams_pv = '../data/nl/ams_data_pv.csv'
df_ams_pv = pd.read_csv(fname_ams_pv)
df_ams_weather.head(30)

,datetime,HoD,dow,doy,month,year,wind_speed,temperature,irradiance,precipitation,cloud_cover,temperature_norm,precipitation_norm,wind_speed_norm,cloud_cover_norm,irradiance_norm
0,2017-04-01 00:00:00,0,5,91,4,2017,3.0,7.6,0.000000,0.0000,0,0.369863,0.000000,0.130435,0.000000,0.000000
1,2017-04-01 01:00:00,1,5,91,4,2017,2.0,7.3,0.000000,0.0000,2,0.363014,0.000000,0.086957,0.222222,0.000000
2,2017-04-01 02:00:00,2,5,91,4,2017,1.0,7.2,0.000000,0.0000,4,0.360731,0.000000,0.043478,0.444444,0.000000
3,2017-04-01 03:00:00,3,5,91,4,2017,3.0,8.4,0.000000,0.0000,8,0.388128,0.000000,0.130435,0.888889,0.000000
4,2017-04-01 04:00:00,4,5,91,4,2017,2.0,7.1,0.000000,0.0000,8,0.358447,0.000000,0.086957,0.888889,0.000000
5,2017-04-01 05:00:00,5,5,91,4,2017,3.0,9.2,11.111111,0.0000,8,0.406393,0.000000,0.130435,0.888889,0.011111
6,2017-04-01 06:00:00,6,5,91,4,2017,4.0,11.3,41.666667,0.0000,8,0.454338,0.000000,0.173913,0.888889,0.041667
7,2017-04-01 07:00:00,7,5,91,4,2017,4.0,12.1,108.333333,0.0000,8,0.472603,0.000000,0.173913,0.888889,0.108333
8,2017-04-01 08:00:00,8,5,91,4,2017,5.0,11.7,125.000000,0.0025,8,0.463470,0.000149,0.217391,0.888889,0.125000
9,2017-04-01 09:00:00,9,5,91,4,2017,4.0,11.0,66.666667,0.1000,8,0.447489,0.005952,0.173913,0.888889,0.066667
10,2017-04-01 10:00:00,10,5,91,4,2017,5.0,12.0,258.333333,0.0025,8,0.470320,0.000149,0.217391,0.888889,0.258333
11,2017-04-01 11:00:00,11,5,91,4,2017,4.0,11.6,163.888889,0.0000,8,0.461187,0.000000,0.173913,0.888889,0.163889
12,2017-04-01 12:00:00,12,5,91,4,2017,4.0,12.4,241.666667,0.0025,8,0.479452,0.000149,0.173913,0.888889,0.241667
13,2017-04-01 13:00:00,13,5,91,4,2017,4.0,13.4,308.333333,0.0000,8,0.502283,0.000000,0.173913,0.888889,0.308333
14,2017-04-01 14:00:00,14,5,91,4,2017,4.0,12.5,219.444444,0.0000,8,0.481735,0.000000,0.173913,0.888889,0.219444
15,2017-04-01 15:00:00,15,5,91,4,2017,3.0,12.4,150.000000,0.0000,8,0.479452,0.000000,0.130435,0.888889,0.150000
16,2017-04-01 16:00:00,16,5,91,4,2017,3.0,11.5,69.444444,0.0000,8,0.458904,0.000000,0.130435,0.888889,0.069444
17,2017-04-01 17:00:00,17,5,91,4,2017,2.0,11.1,25.000000,0.0000,8,0.449772,0.000000,0.086957,0.888889,0.025000
18,2017-04-01 18:00:00,18,5,91,4,2017,2.0,10.0,2.777778,0.0000,8,0.424658,0.000000,0.086957,0.888889,0.002778
19,2017-04-01 19:00:00,19,5,91,4,2017,2.0,9.8,0.000000,0.0000,8,0.420091,0.000000,0.086957,0.888889,0.000000
20,2017-04-01 20:00:00,20,5,91,4,2017,2.0,9.9,0.000000,0.0000,8,0.422374,0.000000,0.086957,0.888889,0.000000
21,2017-04-01 21:00:00,21,5,91,4,2017,3.0,7.9,0.000000,0.0000,8,0.376712,0.000000,0.130435,0.888889,0.000000
22,2017-04-01 22:00:00,22,5,91,4,2017,3.0,7.2,0.000000,0.0000,8,0.360731,0.000000,0.130435,0.888889,0.000000
23,2017-04-01 23:00:00,23,5,91,4,2017,2.0,7.1,0.000000,0.0000,8,0.358447,0.000000,0.086957,0.888889,0.000000
24,2017-04-02 00:00:00,0,6,92,4,2017,2.0,5.9,0.000000,0.0000,4,0.331050,0.000000,0.086957,0.444444,0.000000
25,2017-04-02 01:00:00,1,6,92,4,2017,2.0,5.9,0.000000,0.0000,0,0.331050,0.000000,0.086957,0.000000,0.000000
26,2017-04-02 02:00:00,2,6,92,4,2017,2.0,5.3,0.000000,0.0000,0,0.317352,0.000000,0.086957,0.000000,0.000000
27,2017-04-02 03:00:00,3,6,92,4,2017,2.0,5.7,0.000000,0.0000,0,0.326484,0.000000,0.086957,0.000000,0.000000
28,2017-04-02 04:00:00,4,6,92,4,2017,3.0,5.6,0.000000,0.0000,0,0.324201,0.000000,0.130435,0.000000,0.000000
29,2017-04-02 05:00:00,5,6,92,4,2017,3.0,6.8,22.222222,0.0000,0,0.351598,0.000000,0.130435,0.000000,0.022222

In [4]:
df_ams_weather.head(30)

,datetime,HoD,dow,doy,month,year,wind_speed,temperature,irradiance,precipitation,cloud_cover,temperature_norm,precipitation_norm,wind_speed_norm,cloud_cover_norm,irradiance_norm
0,2017-04-01 00:00:00,0,5,91,4,2017,3.0,7.6,0.000000,0.0000,0,0.369863,0.000000,0.130435,0.000000,0.000000
1,2017-04-01 01:00:00,1,5,91,4,2017,2.0,7.3,0.000000,0.0000,2,0.363014,0.000000,0.086957,0.222222,0.000000
2,2017-04-01 02:00:00,2,5,91,4,2017,1.0,7.2,0.000000,0.0000,4,0.360731,0.000000,0.043478,0.444444,0.000000
3,2017-04-01 03:00:00,3,5,91,4,2017,3.0,8.4,0.000000,0.0000,8,0.388128,0.000000,0.130435,0.888889,0.000000
4,2017-04-01 04:00:00,4,5,91,4,2017,2.0,7.1,0.000000,0.0000,8,0.358447,0.000000,0.086957,0.888889,0.000000
5,2017-04-01 05:00:00,5,5,91,4,2017,3.0,9.2,11.111111,0.0000,8,0.406393,0.000000,0.130435,0.888889,0.011111
6,2017-04-01 06:00:00,6,5,91,4,2017,4.0,11.3,41.666667,0.0000,8,0.454338,0.000000,0.173913,0.888889,0.041667
7,2017-04-01 07:00:00,7,5,91,4,2017,4.0,12.1,108.333333,0.0000,8,0.472603,0.000000,0.173913,0.888889,0.108333
8,2017-04-01 08:00:00,8,5,91,4,2017,5.0,11.7,125.000000,0.0025,8,0.463470,0.000149,0.217391,0.888889,0.125000
9,2017-04-01 09:00:00,9,5,91,4,2017,4.0,11.0,66.666667,0.1000,8,0.447489,0.005952,0.173913,0.888889,0.066667
10,2017-04-01 10:00:00,10,5,91,4,2017,5.0,12.0,258.333333,0.0025,8,0.470320,0.000149,0.217391,0.888889,0.258333
11,2017-04-01 11:00:00,11,5,91,4,2017,4.0,11.6,163.888889,0.0000,8,0.461187,0.000000,0.173913,0.888889,0.163889
12,2017-04-01 12:00:00,12,5,91,4,2017,4.0,12.4,241.666667,0.0025,8,0.479452,0.000149,0.173913,0.888889,0.241667
13,2017-04-01 13:00:00,13,5,91,4,2017,4.0,13.4,308.333333,0.0000,8,0.502283,0.000000,0.173913,0.888889,0.308333
14,2017-04-01 14:00:00,14,5,91,4,2017,4.0,12.5,219.444444,0.0000,8,0.481735,0.000000,0.173913,0.888889,0.219444
15,2017-04-01 15:00:00,15,5,91,4,2017,3.0,12.4,150.000000,0.0000,8,0.479452,0.000000,0.130435,0.888889,0.150000
16,2017-04-01 16:00:00,16,5,91,4,2017,3.0,11.5,69.444444,0.0000,8,0.458904,0.000000,0.130435,0.888889,0.069444
17,2017-04-01 17:00:00,17,5,91,4,2017,2.0,11.1,25.000000,0.0000,8,0.449772,0.000000,0.086957,0.888889,0.025000
18,2017-04-01 18:00:00,18,5,91,4,2017,2.0,10.0,2.777778,0.0000,8,0.424658,0.000000,0.086957,0.888889,0.002778
19,2017-04-01 19:00:00,19,5,91,4,2017,2.0,9.8,0.000000,0.0000,8,0.420091,0.000000,0.086957,0.888889,0.000000
20,2017-04-01 20:00:00,20,5,91,4,2017,2.0,9.9,0.000000,0.0000,8,0.422374,0.000000,0.086957,0.888889,0.000000
21,2017-04-01 21:00:00,21,5,91,4,2017,3.0,7.9,0.000000,0.0000,8,0.376712,0.000000,0.130435,0.888889,0.000000
22,2017-04-01 22:00:00,22,5,91,4,2017,3.0,7.2,0.000000,0.0000,8,0.360731,0.000000,0.130435,0.888889,0.000000
23,2017-04-01 23:00:00,23,5,91,4,2017,2.0,7.1,0.000000,0.0000,8,0.358447,0.000000,0.086957,0.888889,0.000000
24,2017-04-02 00:00:00,0,6,92,4,2017,2.0,5.9,0.000000,0.0000,4,0.331050,0.000000,0.086957,0.444444,0.000000
25,2017-04-02 01:00:00,1,6,92,4,2017,2.0,5.9,0.000000,0.0000,0,0.331050,0.000000,0.086957,0.000000,0.000000
26,2017-04-02 02:00:00,2,6,92,4,2017,2.0,5.3,0.000000,0.0000,0,0.317352,0.000000,0.086957,0.000000,0.000000
27,2017-04-02 03:00:00,3,6,92,4,2017,2.0,5.7,0.000000,0.0000,0,0.326484,0.000000,0.086957,0.000000,0.000000
28,2017-04-02 04:00:00,4,6,92,4,2017,3.0,5.6,0.000000,0.0000,0,0.324201,0.000000,0.130435,0.000000,0.000000
29,2017-04-02 05:00:00,5,6,92,4,2017,3.0,6.8,22.222222,0.0000,0,0.351598,0.000000,0.130435,0.000000,0.022222

In [5]:
df_ams_energy.head(30)

,datetime,Timestamp,HoD,dow,doy,month,year,1011W_pv,1954W_pv,1955A_pv,...,7099P_net,7426U_net,7679U_net,7710F_net,7743P_net,8319Q_net,9248C_net,9370J_net,9506H_net,9991J_net
0,2017-04-02 11:00:00,1491130800,11,6,92,4,2017,NaN,NaN,NaN,...,NaN,NaN,-2045.8,NaN,NaN,NaN,NaN,-1240.7,NaN,NaN
1,2017-04-02 12:00:00,1491134400,12,6,92,4,2017,NaN,NaN,NaN,...,NaN,NaN,-2101.8,NaN,NaN,NaN,NaN,-1220.9,NaN,NaN
2,2017-04-02 13:00:00,1491138000,13,6,92,4,2017,NaN,NaN,NaN,...,NaN,NaN,-1493.1,NaN,NaN,NaN,NaN,-818.0,NaN,NaN
3,2017-04-02 14:00:00,1491141600,14,6,92,4,2017,NaN,NaN,NaN,...,NaN,NaN,-1615.7,NaN,NaN,NaN,NaN,-967.6,NaN,NaN
4,2017-04-02 15:00:00,1491145200,15,6,92,4,2017,NaN,NaN,NaN,...,NaN,NaN,-1240.8,NaN,NaN,NaN,NaN,-860.1,NaN,NaN
5,2017-04-02 16:00:00,1491148800,16,6,92,4,2017,NaN,NaN,NaN,...,NaN,NaN,-548.1,NaN,NaN,NaN,NaN,-412.1,NaN,NaN
6,2017-04-02 17:00:00,1491152400,17,6,92,4,2017,NaN,NaN,NaN,...,NaN,NaN,-33.7,NaN,NaN,NaN,NaN,-6.9,NaN,NaN
7,2017-04-02 18:00:00,1491156000,18,6,92,4,2017,NaN,NaN,NaN,...,NaN,NaN,29.5,NaN,NaN,NaN,NaN,665.3,NaN,NaN
8,2017-04-02 19:00:00,1491159600,19,6,92,4,2017,NaN,NaN,NaN,...,NaN,NaN,31.3,NaN,NaN,NaN,NaN,475.2,NaN,NaN
9,2017-04-02 20:00:00,1491163200,20,6,92,4,2017,NaN,NaN,NaN,...,NaN,NaN,28.9,NaN,NaN,NaN,NaN,55.4,NaN,NaN
10,2017-04-02 21:00:00,1491166800,21,6,92,4,2017,NaN,NaN,NaN,...,NaN,NaN,26.6,NaN,NaN,NaN,NaN,80.1,NaN,NaN
11,2017-04-02 22:00:00,1491170400,22,6,92,4,2017,NaN,NaN,NaN,...,NaN,NaN,20.8,NaN,NaN,NaN,NaN,56.0,NaN,NaN
12,2017-04-02 23:00:00,1491174000,23,6,92,4,2017,NaN,NaN,NaN,...,NaN,NaN,18.9,NaN,NaN,NaN,NaN,67.5,NaN,NaN
13,2017-04-03 00:00:00,1491177600,0,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,16.0,NaN,NaN,NaN,NaN,66.1,NaN,NaN
14,2017-04-03 01:00:00,1491181200,1,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,14.4,NaN,NaN,NaN,NaN,40.7,NaN,NaN
15,2017-04-03 02:00:00,1491184800,2,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,14.6,NaN,NaN,NaN,NaN,69.8,NaN,NaN
16,2017-04-03 03:00:00,1491188400,3,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,14.4,NaN,NaN,NaN,NaN,61.0,NaN,NaN
17,2017-04-03 04:00:00,1491192000,4,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,22.6,NaN,NaN,NaN,NaN,222.3,NaN,NaN
18,2017-04-03 05:00:00,1491195600,5,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,19.5,NaN,NaN,NaN,NaN,583.9,NaN,NaN
19,2017-04-03 06:00:00,1491199200,6,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,-59.1,NaN,NaN,NaN,NaN,40.2,NaN,NaN
20,2017-04-03 07:00:00,1491202800,7,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,-200.9,NaN,NaN,NaN,NaN,-6.4,NaN,NaN
21,2017-04-03 08:00:00,1491206400,8,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,-360.9,NaN,NaN,NaN,NaN,-287.1,NaN,NaN
22,2017-04-03 09:00:00,1491210000,9,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,-492.4,NaN,NaN,NaN,NaN,-457.7,NaN,NaN
23,2017-04-03 10:00:00,1491213600,10,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,-602.6,NaN,NaN,NaN,NaN,-557.9,NaN,NaN
24,2017-04-03 11:00:00,1491217200,11,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,-713.7,NaN,NaN,NaN,NaN,-632.8,NaN,NaN
25,2017-04-03 12:00:00,1491220800,12,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,-992.5,NaN,NaN,NaN,NaN,-867.4,NaN,NaN
26,2017-04-03 13:00:00,1491224400,13,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,-1555.7,NaN,NaN,NaN,NaN,-1140.1,NaN,NaN
27,2017-04-03 14:00:00,1491228000,14,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,-1663.4,NaN,NaN,NaN,NaN,-1205.6,NaN,NaN
28,2017-04-03 15:00:00,1491231600,15,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,-1192.6,NaN,NaN,NaN,NaN,-817.2,NaN,NaN
29,2017-04-03 16:00:00,1491235200,16,0,93,4,2017,NaN,NaN,NaN,...,NaN,NaN,-509.6,NaN,NaN,NaN,NaN,-382.1,NaN,NaN

## Add weather data to ams energy data

In [6]:
df_ams_weather.columns

Index(['datetime', 'HoD', 'dow', 'doy', 'month', 'year', 'wind_speed',
       'temperature', 'irradiance', 'precipitation', 'cloud_cover',
       'temperature_norm', 'precipitation_norm', 'wind_speed_norm',
       'cloud_cover_norm', 'irradiance_norm'],
      dtype='object')

In [7]:
# print the shape of df_ams_weather, df_ams_energy and df_ams, using one fstring
print(
    f'Shape of df_ams_weather: {df_ams_weather.shape} \nShape of df_ams_energy is {df_ams_energy.shape}')

Shape of df_ams_weather: (17520, 16)
Shape of df_ams_energy is (16960, 88)

In [8]:
# Merge weather data and energy data into one dataframe called df_ams
# based on df_ams_energy
# add irradiance, temperature, could_cover, wind_speed, and precipitation, and their normalized features it, in total 10 features
# then obtain df_ams, which should have a shape of (16960,88+10)
# pay attention to the duplicate columns of time horizon:['HoD', 'dow', 'doy', 'month', 'year']
df_ams = pd.merge(df_ams_weather, df_ams_energy, on=None, how='inner')
# the parameter "on" was set to None, which means that the merge will be based on the common columns in the two dataframes

In [9]:
df_ams_pv.columns

Index(['datetime', 'Timestamp', 'HoD', 'dow', 'doy', 'month', 'year', '1011W',
       '1954W', '1955A', '1964J', '2053G', '2108P', '2442E', '3070L', '3307S',
       '3517V', '3660D', '3726A', '3932W', '4226R', '4451M', '5427W', '5815T',
       '7099P', '7426U', '7679U', '7710F', '7743P', '8319Q', '9248C', '9370J',
       '9506H', '9991J'],
      dtype='object')

In [10]:
# do the same for the dataframes that stores the PV, consumption and net load separately
df_ams_pv = pd.merge(df_ams_weather, df_ams_pv, on=None, how='inner')
df_ams_con = pd.merge(df_ams_weather, df_ams_energy, on=None, how='inner')
df_ams_net = pd.merge(df_ams_weather, df_ams_energy, on=None, how='inner')

In [11]:
df_ams_pv.columns

Index(['datetime', 'HoD', 'dow', 'doy', 'month', 'year', 'wind_speed',
       'temperature', 'irradiance', 'precipitation', 'cloud_cover',
       'temperature_norm', 'precipitation_norm', 'wind_speed_norm',
       'cloud_cover_norm', 'irradiance_norm', 'Timestamp', '1011W', '1954W',
       '1955A', '1964J', '2053G', '2108P', '2442E', '3070L', '3307S', '3517V',
       '3660D', '3726A', '3932W', '4226R', '4451M', '5427W', '5815T', '7099P',
       '7426U', '7679U', '7710F', '7743P', '8319Q', '9248C', '9370J', '9506H',
       '9991J'],
      dtype='object')

In [12]:
# print the shape of df_ams_weather, df_ams_energy and df_ams, using one fstring
print(
    f'Shape of df_ams_weather: {df_ams_weather.shape} \nShape of df_ams_energy is {df_ams_energy.shape} \nShape of df_ams {df_ams.shape}')

Shape of df_ams_weather: (17520, 16)
Shape of df_ams_energy is (16960, 88)
Shape of df_ams (16960, 98)

In [13]:
# get the different columns between df_ams and df_ams_energy
# and print the different columns
diff_cols = set(df_ams.columns)-set(df_ams_energy.columns)
print(diff_cols)

{'temperature_norm', 'wind_speed_norm', 'irradiance', 'cloud_cover', 'cloud_cover_norm', 'irradiance_norm', 'precipitation_norm', 'precipitation', 'wind_speed', 'temperature'}

# Save the dataframe to a csv file

In [14]:
df_ams.to_csv('../data/nl/ams_data_merged_unprocessed.csv', index=False)

In [15]:
df_ams_pv.to_csv('../data/nl/ams_data_pv_merged.csv', index=False)
df_ams_con.to_csv('../data/nl/ams_data_con_merged.csv', index=False)
df_ams_net.to_csv('../data/nl/ams_data_net_merged.csv', index=False)